#include <stdlib.h>
#include <algorithm>
#include <random>
#include <chrono>
#include <iostream>

constexpr int alignment=32;

template<typename T,int Alignment>
/*
 * Dynamically allocate un-initialized storage where the storage is 
 * aligned according to Alignment i.e the storage starts at an adrress 
 * that should be divisible with Alignment 
 *
 * This is usefull for arrays of simple types like 
 *
 *  
 * Notes :
 * For fixed size buffers i.e when the size is known at runtime prefer : 
 * std::aligned_storage/std::align
 *
 *  In principle in C++17 the call to posix_memalign and the placement new can be avoided 
 *  in favour of the "new operator" alignment aware overloads. Needs some checking on library support.
 */

class AlignedDynArray
{
public:
  AlignedDynArray() = delete;
  AlignedDynArray(AlignedDynArray const&) = delete;
  AlignedDynArray& operator=(AlignedDynArray const&) = delete;
  AlignedDynArray(AlignedDynArray&&) = delete;
  AlignedDynArray& operator=(AlignedDynArray&&) = delete;

  explicit AlignedDynArray(size_t n);
  ~AlignedDynArray();

  ///conversions to T*
  operator T*(); 
  operator const T*() const; 

  /// index array operators  
  T& operator [](const std::size_t pos);
  const T& operator [](const std::size_t pos) const ;

  ///size of allocated buffer
  std::size_t size() const;

private:
  T*  m_buffer=nullptr;
  void* m_raw=nullptr;
  size_t const m_size=0;
}; 


template<typename T, int Alignment>
inline
AlignedDynArray<T,Alignment>::AlignedDynArray(size_t n): m_buffer(nullptr), 
  m_raw(nullptr),
  m_size(n){
    size_t const size = n * sizeof(T) +alignof(T) ;
    //create buffer of right size,properly aligned
    posix_memalign(&m_raw, Alignment, size);
    //placement new of elements to the buffer
    m_buffer = new (m_raw) T[n];
  }

template<typename T, int Alignment>
inline  
AlignedDynArray<T,Alignment>::~AlignedDynArray(){
  for (std::size_t pos = 0; pos < m_size; ++pos) {
    m_buffer[pos].~T();
  }
  free(m_buffer);
}

template<typename T, int Alignment>
inline   
AlignedDynArray<T,Alignment>::operator T*() {return m_buffer;} 

template<typename T, int Alignment>
inline   
AlignedDynArray<T,Alignment>::operator const T*() const {return m_buffer;}

template<typename T, int Alignment>
inline  
T& AlignedDynArray<T,Alignment>::operator[] (const std::size_t pos) { return m_buffer[pos];}

template<typename T, int Alignment>
inline  
const T& AlignedDynArray<T,Alignment>::operator[] (const std::size_t pos) const { return m_buffer[pos];}

template<typename T, int Alignment>
inline  
std::size_t AlignedDynArray<T,Alignment>::size() const {return m_size;}

///

size_t findMinimumIndex1(float* __restrict arrayIn, const size_t n){  
  float* array = (float*)__builtin_assume_aligned(arrayIn, alignment);
  float minimum = array[0]; 
  size_t minIndex=0;
  for (size_t i=0 ; i<n ; ++i){ 
    if(array[i]<minimum){
      minimum=array[i];
      minIndex=i;
    }     
  }
  return minIndex;
} 


size_t findMinimumIndex2(float* __restrict arrayIn, const size_t n){  
  float* array = (float*)__builtin_assume_aligned(arrayIn, alignment);
  return std::distance(array, std::min_element(array, array+n));
}


int main(){

  //Fill array
  //std::random_device rd;
  //std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
  std::mt19937 gen; //Standard mersenne_twister_engine seeded with rd()

  std::uniform_real_distribution<> dis(1.0, 10.0);
  std::uniform_int_distribution<> disint(70, 80);
  const size_t n= disint(gen);
  const size_t nn= n*(n-1)/2;
  AlignedDynArray<float,alignment> array(nn);

  for (size_t i = 0; i < nn; ++i) {
    // Use dis to transform the random unsigned int generated by gen into a
    // double. Each call to dis(gen) generates a new random double
    array[i]=dis(gen);
  }


  //1.
  { 
    //Test simple C-style solution
    std::cout << "--------------------------------" <<'\n';
    std::cout << "-- findMinimumIndex1 ---" <<'\n'; 
    //Time it
    std::chrono::steady_clock::time_point clock_begin = std::chrono::steady_clock::now();
    auto index=findMinimumIndex1(array,nn);
    std::chrono::steady_clock::time_point clock_end = std::chrono::steady_clock::now();
    std::chrono::steady_clock::duration diff = clock_end - clock_begin;
    //print 
    std::cout <<"Time: " << std::chrono::duration <double, std::nano> (diff).count() << "ns" << '\n';
    std::cout << "Minimum index " << index <<  " with value " <<array[index]<<'\n'; 
    std::cout << "--------------------------------" <<'\n';
  }

  //2.
  { 
    std::cout << "--------------------------------" <<'\n';
    std::cout << "--  findMinimumIndex2  ---" <<'\n'; 
    //Time it
    std::chrono::steady_clock::time_point clock_begin = std::chrono::steady_clock::now();
    auto index=findMinimumIndex2(array,nn);
    std::chrono::steady_clock::time_point clock_end = std::chrono::steady_clock::now();
    std::chrono::steady_clock::duration diff = clock_end - clock_begin;
    //print 
    std::cout <<"Time: " << std::chrono::duration <double, std::nano> (diff).count() << "ns" << '\n';
    std::cout << "Minimum index " << index <<  " with value " <<array[index]<<'\n'; 
    std::cout << "--------------------------------" <<'\n';
  }


}
